on: 
  workflow_dispatch:
  schedule:
    - cron: 25 5 * * 2
    
name: produce_updated_matrix

jobs:
  departures_slice_0500:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        if: steps.cache_osm.outputs.cache-hit != 'true'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("devtools"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download network.dat
        run: |
          curl -LJ https://github.com/stupidpupil/wales_ish_otp_graph/releases/latest/download/r5r_network_dat.zip -o data/r5r_network_dat.zip
          cd data
          unzip r5r_network_dat.zip
          mv r5r_network_dat/network.dat network.dat
          cd ..

      - name: Download trip points
        run: |
          curl https://raw.githubusercontent.com/stupidpupil/wales_lsoa_trip_points/points-releases/lsoa11_nearest_road_points.geojson -o data/lsoa11_nearest_road_points.geojson

      - name: Produce departures slice
        run: |
          options(java.parameters = "-Xmx12G")
          devtools::load_all()
          produce_departures_slice(next_tuesday("05:00"))
        shell: Rscript {0}

      - name: Upload slice artifact
        uses: actions/upload-artifact@v2
        with:
          name: departures_slice_0500
          path: output/departures_slice_*.rds
          if-no-files-found: error

  departures_slice_1100:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        if: steps.cache_osm.outputs.cache-hit != 'true'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("devtools"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download network.dat
        run: |
          curl -LJ https://github.com/stupidpupil/wales_ish_otp_graph/releases/latest/download/r5r_network_dat.zip -o data/r5r_network_dat.zip
          cd data
          unzip r5r_network_dat.zip
          mv r5r_network_dat/network.dat network.dat
          cd ..

      - name: Download trip points
        run: |
          curl https://raw.githubusercontent.com/stupidpupil/wales_lsoa_trip_points/points-releases/lsoa11_nearest_road_points.geojson -o data/lsoa11_nearest_road_points.geojson

      - name: Produce departures slice
        run: |
          options(java.parameters = "-Xmx12G")
          devtools::load_all()
          produce_departures_slice(next_tuesday("11:00"))
        shell: Rscript {0}

      - name: Upload slice artifact
        uses: actions/upload-artifact@v2
        with:
          name: departures_slice_1100
          path: output/departures_slice_*.rds
          if-no-files-found: error

  departures_slice_1700:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        if: steps.cache_osm.outputs.cache-hit != 'true'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("devtools"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download network.dat
        run: |
          curl -LJ https://github.com/stupidpupil/wales_ish_otp_graph/releases/latest/download/r5r_network_dat.zip -o data/r5r_network_dat.zip
          cd data
          unzip r5r_network_dat.zip
          mv r5r_network_dat/network.dat network.dat
          cd ..

      - name: Download trip points
        run: |
          curl https://raw.githubusercontent.com/stupidpupil/wales_lsoa_trip_points/points-releases/lsoa11_nearest_road_points.geojson -o data/lsoa11_nearest_road_points.geojson

      - name: Produce departures slice
        run: |
          options(java.parameters = "-Xmx12G")
          devtools::load_all()
          produce_departures_slice(next_tuesday("17:00"))
        shell: Rscript {0}

      - name: Upload slice artifact
        uses: actions/upload-artifact@v2
        with:
          name: departures_slice_1700
          path: output/departures_slice_*.rds
          if-no-files-found: error

  matrix_update:
    needs: [
      'departures_slice_0500',
      'departures_slice_1100',
      'departures_slice_1700']
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        if: steps.cache_osm.outputs.cache-hit != 'true'

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("devtools"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Download departures_slice_0500 artifact
        uses: actions/download-artifact@v2
        with:
          name: departures_slice_0500
          path: output

      - name: Download departures_slice_1100 artifact
        uses: actions/download-artifact@v2
        with:
          name: departures_slice_1100
          path: output

      - name: Download departures_slice_1700 artifact
        uses: actions/download-artifact@v2
        with:
          name: departures_slice_1700
          path: output

      - name: Download OSRM-runner outputs
        run: |
          curl https://raw.githubusercontent.com/stupidpupil/wales_ish_osrm_runner/matrix-releases/index.json -o output/index.json
          curl https://raw.githubusercontent.com/stupidpupil/wales_ish_osrm_runner/matrix-releases/arrive_by_0900_driving.csv -o output/arrive_by_0900_driving.csv

      - name: Produce matrices
        run: |
          devtools::load_all()
          journeys <- joined_slices() %>% filter_to_most_efficient_departures()
          journeys %>% write_arrive_by_matrix_csv(next_tuesday("09:00"), pre_sorted = TRUE)
          journeys %>% write_arrive_by_matrix_csv(next_tuesday("11:00"), pre_sorted = TRUE)
          journeys %>% write_arrive_by_matrix_csv(next_tuesday("15:00"), pre_sorted = TRUE)
          journeys %>% write_arrive_by_matrix_csv(next_tuesday("17:00"), pre_sorted = TRUE)
          write_metadata_from_index_to_csv_comments()
        shell: Rscript {0}

      - name: Checkout matrix-releases branch
        uses: actions/checkout@v2
        with:
          ref: matrix-releases
          path: matrix-releases

      - name: Copy matrices and commit
        run: |
          cd matrix-releases
          rm -f *.csv
          rm -f index.json
          cp ../output/*.csv .
          cp ../output/index.json .
          git config user.name "Graph Release Bot"
          git config user.email "<>"
          git add .
          git commit -m "Updated for new release"
          git push origin matrix-releases
          cd ..
